language: node_js
node_js:
- '7'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8 - g++-4.8
env:
- CXX=g++-4.8
deploy:
  provider: heroku
  api_key:
    secure: "fqoCidYH5IR+MN98A+wAsJTHqAHoJ/nWDakHszSrRzVcCp0JL1KbDCKytRDzPZa5iBkGrZhsNwhWwNrWZSj1ZwqAp+fBVCIM7esB87kH8GPwDtBmraVqapqR3lnPNeozHSXFIG3+NA06Zh5tRLIEw+d97K+NMtq4tzLStlcEfWZ1d+vLvt9k+szvK0xP04gb/36dlUeyNlWGnwP7ch/4M2xmh5UQ9ioF1icoCx/BcMlD1IZJMVML396rV5hh8+pvr/hZL889f6cs0D012SDqp7hw800OWnUdaucmLsbmPmTEZIJZZUmVzzCtAYYl+aErU1XmrKtmIEf35t0ywAR1k/6dvVedqsQjsW6hjFAO1In7NVY1rHn9DKa70poss1ekRwKlAkeXnMyq0onTmiGouQB890JLG3u0ioetkE6ylTN5oqVPHS3B2eeHOwpD0WuCBcGJRjxa6axI64iMIyFhSz74L7vG1EUo91JdhoHJg8xn0/BIhEsO4nPOV7k/v85Wl5yIb1AS2PZc0frfXiWKxeFmBX+nVWr94PdDYS2tlW8NsfBoLrZJFzANf1ynaTQ36o8SDmMHfZpCT8vcCeKL22vfbQSOXSGpn58WqlUqq8o5vp8STR6PXYR3g5iGEDrs3YDfzkPygJoEjkIboHbXfbc78LMabOGU+LW9Bzzs53o="
  app: tentamenmm
  on:
    branch: master
