language: node_js
node_js:
- '7'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8 - g++-4.8
env:
- CXX=g++-4.8
deploy:
  provider: heroku
  api_key:
    secure: "vdFfxKeda857OAFeA4vODjxHpqGEnbYClCn+fCCveHB/WJ6MdLLDakGlOsHlykZ6ZOTC47Njq7nBaZT9Oz9xeDAsM+Q/MYZe0GuzuOO3WEc5lXZehTiSU64e1C1bNHknxiQa11s78aVp/bO5Ln861pAFAh/HM84BycrLkQCUDrTNw3vuHHc9XtPBTplidLuOsIhhNjpUXeR3JR/k4QeC58Yo6v5kYEAaz8ol2nr2pbMZ1Yki3qoPLpJxew8HLjcQKZ01+ES3o2FSm4KzV3SAvjLhAEu8wsfeY9jPv8f6ts3Cd2/lx6tZslhkrVnp9cwquLxdH41PZ21Qaea7wzAWZMYMBkvJB5cO2b15jhT8nT+EGUadJM/bK3z57Z2ZlDQYAtvQgxg5eCZNxm1pGIbduRkUAZTStnDmAHPMho+hTdsu3FS1IdpEA1LXt6Fk2JNtsCRVh3XyLQlsXrdarVpnOq9WcYRvyWnbF4K3dA1crkApN2JjwfwW4TNKESZ67vglLYvAkfjqaxnql9rbYpM8fi+2TdpX3fGEAf09iUYMYUz9Rg73zVb0FtXwSaKdf7GC0vVi1EEasojOWuWYOH9RXr9qM7SUx2Pn2KtSvXFrO7OfNDZgN7kWnpzSsI2+mUOG16dD6czwxeW8aIcATL2h5MOMxY918DsyuDkM1UkH7OU="
  app: tentamenmm
  on:
    branch: master
